# Generated by Django 4.2.2 on 2023-07-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard_app_main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AxisFeedrate2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "component",
                    models.CharField(blank=True, default=None, max_length=100),
                ),
                ("component_name", models.CharField(blank=True, max_length=100)),
                ("component_id", models.CharField(blank=True, max_length=100)),
                ("timestamp", models.DateTimeField(blank=True)),
                ("name", models.CharField(blank=True, max_length=100)),
                ("sequence", models.IntegerField(blank=True)),
                ("value", models.FloatField(blank=True)),
            ],
        ),
    ]
