# Generated by Django 4.2.2 on 2023-07-29 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard_app_main", "0002_axisfeedrate2"),
    ]

    operations = [
        migrations.RenameField(
            model_name="axisfeedrate2", old_name="name", new_name="dataItemId",
        ),
    ]
