# Generated by Django 4.2.2 on 2023-08-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard_app_main", "0003_rename_name_axisfeedrate2_dataitemid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Temperature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("composition_id", models.CharField(blank=True, max_length=100)),
                ("timestamp", models.DateTimeField(blank=True)),
                ("sequence", models.IntegerField(blank=True)),
                ("value", models.FloatField(blank=True)),
            ],
        ),
    ]
